### ISSUE TITLE
UEF Experimental Aircraft Carrier no AA

### ISSUE THREAD

**Issue by GreeyChip** [LOUD-Project/Git-LOUD#126]
The AA does not work on the UEF Experimental Aircraft Carrier

**Comment by Sprouto** [comment]
Apparently, the weapon blueprint value 'AboveWaterFireOnly = true' does NOT function as advertised.   The bone, on which the AA weapon is mounted, is clearly above the waterline, and should fire, but it has become clear that this is simply not enough, in some cases.

Removing this blueprint value, or setting it to false, allows the AA weapons to fire again.   The ability for the AA weapons to fire is also controlled by the layers, so in this case, the AA weapon is only allowed to fire when the unit is on the 'water' layer, as opposed to the 'sub' layer when it is submerged.
