### ISSUE TITLE
Draft optional AI faction randomization method to minimize identical factions

### ISSUE THREAD

**Issue by joinr** [LOUD-Project/Git-LOUD#23]
Per some discussion with Rat Circus on discord, I am looking at adding an option to ensure variety in random factions while respecting user conditions.  Looking into the lobby code, it seems faction selection is completely within mod control from lua.  So I am working on adding a game option that provides and alternate random faction selection where the goal is to ensure an even representation of factions.  We basically build a frequency table of the user selected factions, choose a random order to assign factions to the remaining random players, and then deal out factions.  We pick from the minimum frequency, and use random draws to sort ties, then update the frequencies based on selection.  As the sample output shows, this forces a more varied field where all the factions are guaranteed to have representation, and the possibility of everyone playing the same faction is not possible (I kept getting those kinds of seemingly improbable games, which prompted looking at an alternate means to randomize).  There is still randomization in the factions chosen and the player assignment.  Not shown is the draft integration code with a simple Game Options checkbox, and the alternate code path wired into the lobby source file to check for this option.  I got the algorithm settled (and picked up some rudimentary lua in the process - not my first or even fifth language) and verified though (follows):

```lua
--sample data extrapolated from LOUD lobby and AssignRandomFactions
randomfac = 5
players = {5,5,1,5,5,4,5,5,3,5,5,2}
small    = {1,5,5,5} --typical


--utils 

-- Print contents of `tbl`, with indentation.
-- `indent` sets the initial level of indentation.
function tprint (tbl, indent)
  if not indent then indent = 0 end
  for k, v in pairs(tbl) do
    formatting = string.rep("  ", indent) .. k .. ": "
    if type(v) == "table" then
      print(formatting)
      tprint(v, indent+1)
    elseif type(v) == 'boolean' then
      print(formatting .. tostring(v))      
    else
      print(formatting .. v)
    end
  end
end

--compute a frequency table from a table's values.
function vfreqs(tbl)
    local res = {}
    for k,v in pairs(tbl) do
        if not res[v] then 
            res[v] = 1
        else 
            res[v] = res[v]+1
        end
    end
    return res
end

function exclude(tbl, v)
   local res = {}
   for k,d in pairs(tbl) do
        if v == d then
           
        else
           res[k] = d
        end 
   end
   return res
end

function filter(tbl, v)
   local res = {}
   for k,v2 in pairs(tbl) do
       if  v == v2 then
           res[k] = v2
       end
   end
   return res
end

function keys(tbl)
    res = {}
    for k,v in pairs(tbl) do 
        table.insert(res,k)
    end 
    return res
end

function shuffle(tbl)
  for i = #tbl, 2, -1 do
    local j = math.random(i)
    tbl[i], tbl[j] = tbl[j], tbl[i]
  end
  return tbl
end

--implementation 

function draw(fs)
    local least = 1000000
    local candidates = {}
    for e,v in pairs(fs) do 
        if v < least then 
            least = v
            candidates = {} 
            table.insert(candidates,e)
        elseif v == least then  
            table.insert(candidates,e)
        end
    end
    local idx = math.random(table.getn(candidates))
    local choice = candidates[idx]
    fs[choice] = fs[choice] + 1
    return choice
end 

--ensure we have 0 recorded for factions in the
--frequency table that weren't selected yet.
function zeroes(fs)
    for i=1,4,1 do
        if not fs[i] then 
            fs[i] = 0
        end
    end
    return fs
end 

--given an array of player faction selections, 
--builds a frequency table and traverses the random
--players.  Each random player is dealt a selection
--from the least-frequent faction at the time.  If
--there are multiple candidates, we do a random 
--draw to determine which is selected.  After 
--each draw, we update the frequency table to 
--ensure de-duplication of factions until 
--frequencies are even.  This should evenly
--distribute the random factions while accounting
--for the existing user selection while maintaining
--variety in representation.  We can easily
--tweak this to bias toward distributions and the
--like.  We don't take location into account, since
--map placement is varied.  So it's possible to 
--have disparate factions working together on the
--same side of the map.
function assignments(ps)
    local fs = zeroes(vfreqs(exclude(ps,randomfac)))
    local order = shuffle(keys(filter(ps,randomfac)))
    local choices = {}
    for k, playerindex in pairs(order) do
        choices[playerindex] = draw(fs)
    end
    for k,faction in pairs(ps) do
        if not choices[k] then 
            choices[k] = faction
        end
    end
    return choices
end 
--sample output

-->tprint(assignments(small))
--1: 1
--2: 4
--3: 3
--4: 2
-->tprint(assignments(small))
--1: 1
--2: 2
--3: 4
--4: 3
-->tprint(assignments(small))
--1: 1
--2: 3
--3: 4
--4: 2
-->tprint(assignments(small))
--1: 1
--2: 2
--3: 3
--4: 4
-->tprint(assignments(small))
--1: 1
--2: 2
--3: 4
--4: 3
-->tprint(assignments(small))
--1: 1
--2: 4
--3: 2
--4: 3
-->tprint(assignments(small))
--1: 1
--2: 2
--3: 4
--4: 3

-->tprint(assignments(players))
--1: 3
--2: 2
--3: 1
--4: 3
--5: 4
--6: 4
--7: 1
--8: 2
--9: 3
--10: 4
--11: 1
--12: 2
-->tprint(assignments(players))
--1: 3
--2: 1
--3: 1
--4: 1
--5: 2
--6: 4
--7: 2
--8: 4
--9: 3
--10: 3
--11: 4
--12: 2
-->tprint(assignments(players))
--1: 4
--2: 3
--3: 1
--4: 2
--5: 1
--6: 4
--7: 1
--8: 2
--9: 3
--10: 4
--11: 3
--12: 2

--frequencies are evenly distributed.

-->tprint(vfreqs(assignments(players)))
--1: 3
--2: 3
--3: 3
--4: 3
-->tprint(vfreqs(assignments(players)))
--1: 3
--2: 3
--3: 3
--4: 3

--->tprint(vfreqs(assignments(small)))
--1: 1
--2: 1
--3: 1
--4: 1
--
--->tprint(vfreqs(assignments(small)))
--1: 1
--2: 1
--3: 1
--4: 1
```

**Comment by joinr** [comment]
Got it working and tested.
[patch.diff](https://github.com/LOUD-Project/Git-LOUD/files/5790409/patch.diff.txt) implements a gameplay option.

The following table demonstrates some of the tendency toward duplication I see in typical small-N games (I play 4 player a lot with 3 AI, the samples are somewhat representative, although recently even more duplication/triplication has seemed to pop up).  When the option is enabled, we see a consistent representation amongst all factions, albeit with random assignments to different players.

# Location

-   Options
    -   Gameplay
        -   Evenly Distribute Random Factions [very bottom]

# Sample debug output

    INFO: *RandomFactions - Assigned Player:1 Faction:1
    INFO: *RandomFactions - Assigned Player:2 Faction:4
    INFO: *RandomFactions - Assigned Player:3 Faction:4
    INFO: *RandomFactions - Assigned Player:4 Faction:2
    INFO: *RandomFactions - Assigned Player:5 Faction:2
    INFO: *RandomFactions - Assigned Player:6 Faction:1
    INFO: *RandomFactions - Assigned Player:7 Faction:2
    INFO: *RandomFactions - Assigned Player:8 Faction:3
    INFO: *RandomFactions - Assigned Player:9 Faction:3
    INFO: *RandomFactions - Assigned Player:10 Faction:4
    INFO: *RandomFactions - Assigned Player:11 Faction:1
    INFO: *RandomFactions - Assigned Player:12 Faction:3
    INFO: *RandomFactions - Faction -> Frequency = {1 = 3, 2 = 3, 3 = 3, 4 = 3}


# Sample draws

| Player | Draw         | UEF | Cybran | Aeon | Seraphim | Spread? |
|--------|--------------|-----|--------|------|----------|---------|
| u      | uccucasusasa |   3 |      3 |    3 |        3 | false   |
| u      | uccuaasssuca |   3 |      3 |    3 |        3 | false   |
| u      | cacaasauacuu |   3 |      3 |    5 |        1 | false   |
| u      | uccuccascsac |   2 |      6 |    2 |        2 | false   |
| u      | cuus         |   2 |      1 |    1 |        0 | false   |
| u      | uucu         |   3 |      1 |    0 |        0 | false   |
| u      | uscc         |   1 |      2 |    0 |        1 | false   |
| u      | assucucacsau |   3 |      3 |    3 |        3 | true    |
| u      | uscasacuasuc |   3 |      3 |    3 |        3 | true    |
| u      | asaucsccasuu |   3 |      3 |    3 |        3 | true    |
| u      | ucaucuaasscs |   3 |      3 |    3 |        3 | true    |
| u      | aucs         |   1 |      1 |    1 |        1 | true    |
| u      | suca         |   1 |      1 |    1 |        1 | true    |
| u      | uacs         |   1 |      1 |    1 |        1 | true    |

**Comment by TheRatCircus** [comment]
Integrated in 8a1f32f, which closes this.
