### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Americanzer0** [LOUD-Project/Git-LOUD#39]
When launching LOUD updater within Arch based linux using proton-tricks, launcher runs but indicates the below error and does not download required game data after making directories:

Connecting to FTP...Error: EINVAL: invalid argument, uv_pipe_open

**Comment by TheRatCircus** [comment]
The updater's maintainer is no longer active on the team, and it was also never developed or tested for any Linux distro. For now, check https://github.com/LOUD-Project/Git-LOUD/issues/31 for a workaround.

**Comment by TheRatCircus** [comment]
A Bash script could replace the launcher in full, but to have even the basic features would involve multiple dozens of hours of work to service a tiny subset of the player base, all of whom already have alternative ways of doing what the launcher does.

It is also worth noting that the only one who would do this would be me, and I'm currently too busy.

**Comment by AnaxMorden** [comment]
Got Linux support working with Git version:
Follow the steps from the Readme, but dont create a shortcut.
Instead use this .desktop file ( replace .txt with .desktop )
[LOUD MOD.txt](https://github.com/LOUD-Project/Git-LOUD/files/7697341/LOUD.MOD.txt)

You will need to update it manually and manually install maps from windows, but it fully works

**Comment by TheRatCircus** [comment]
> Got Linux support working with Git version: Follow the steps from the Readme, but dont create a shortcut. Instead use this .desktop file ( replace .txt with .desktop ) [LOUD MOD.txt](https://github.com/LOUD-Project/Git-LOUD/files/7697341/LOUD.MOD.txt)
> 
> You will need to update it manually and manually install maps from somewhere, but it fully works

This is more-or-less what I do, so I'm going to close this issue and direct people to it if they have similar questions for now. Thanks for this.
