### ISSUE TITLE
Game Stuck since update of lua.scd on 10th October 2021

### ISSUE THREAD

**Issue by Nightstalker81** [LOUD-Project/Git-LOUD#40]
AI seams to be building just Scouts, Build Units (Engineers, Sup Commanders, etc.) and Buildings.
Game-Points are stuck at zero and also unit cap ist not displayed correctly (0/0 through the whole game).
Own units seem to be "out of control" (e.g. leaving patrol routes to "chase" units to enemy base).
Workaround at the moment is to use the "lua.scd" prior to 10th October (Version less than 5.4.37).

**Comment by Garanas** [comment]
There was no patch on the 10th of October. We (FAF) also do not use .scd files, but .nxt. What update are you referring to? Did steam launch an update?

**Comment by Sprouto** [comment]
This issue was resolved in Ver 5.4.39.
