### ISSUE TITLE
Ships movement

### ISSUE THREAD

**Issue by vongratz** [LOUD-Project/Git-LOUD#41]
Several times, some mods, including my one, that never come to light, changed speed and maneuver coeficients to be more real and work better. One thing I have noted, is that, from the Supcomm vanilla to FA, the change was to remove any acelleration coeficient, AND the guy or guys that done ships movements, dont have any idea of they are doing. So, I think that any "chimmy " of the ships would be because this.They obviously mistaken  TURN RADIUS AND TURN RATE, what can do a lot of desnecessary entries for each movement.

**Comment by Sprouto** [comment]
This is quite true - a lot of the ships, and land units as well, have unnatural acceleration and turn rates.

**Comment by vongratz** [comment]
Could this be implemented ?  Several "classes" of acelerations can exist: Hovers, for example had the longer stop time.

**Comment by Sprouto** [comment]
Each blueprint has a value for braking speed, so yes - it is indeed possible.

**Comment by Sprouto** [comment]
On many of our larger ships, in LOUD, we have reduced the acceleration and braking factors so that they require several seconds to reach top speed - or stop.   This just makes sense, and it's something we also apply, but not rigidly, to the heaviest land units as well.

**Comment by vongratz** [comment]
Ive done in my personal mod. Appears to me that the ships movement behavior are improved. What you think?

**Comment by vongratz** [comment]
yes i will do


Em qui., 4 de jul. de 2024 às 11:13, Sprouto ***@***.***>
escreveu:
