### ISSUE TITLE
Add the ability to scale the user interface

### ISSUE THREAD

**Issue by niriak** [LOUD-Project/Git-LOUD#95]
First of all, thank you for your great work!

It would be nice if you could scale the UI in LOUD. For example, the font is quite small at higher resolutions.

I have seen that this is possible in FAF and have made an attempt to port some of the missing parts of the scaling code to LOUD. I'm not sure who to ask at FAF yet, but assuming nobody objects, I could try to work on a first PR. Is there any interest?

**Comment by Sprouto** [comment]
We've already obtained permission to use this - but have no one to follow thru - so, please, if you wish - by all means.

**Comment by binarybubble** [comment]
Join our Discord: https://discord.com/invite/ZCC6tns6vb

**Comment by Sprouto** [comment]
I'll give it a look over today.

**Comment by Sprouto** [comment]
You and me both - but I seem to have overcome it - I am testing it now - so far so good - any particular areas where you have some concerns ?

**Comment by Sprouto** [comment]
Set to 275% - scaling is stable in lobby - will continue to work at this setting for the timebeing.   I will go thru create process in Matchmaking lobby.

**Comment by Sprouto** [comment]
The lobby continues to look flawless at 275%.   Of course, while working with this, I have detected a lobby flaw that I introduced myself with my latest lobby work.

In game, both the standard and supreme scoreboard are malfunctioning at 275%.   I wasn't quite prepared for unit icons to be so small either - but I don't think that's a scaling issue but more one of which icon set the user has (I have the medium sized set installed).

**Comment by Sprouto** [comment]
Yes - I can certainly do that - but it will be easier for me to post those on our Discord - than it is here.
